config/routes.rb
Rails.application.routes.draw do
 
      root :to => "events#index"
    get '/signup' => 'homes#new'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    resources :users do
      collection do
        get :forget_password
        patch :change_password
      end
    end
    resources :homes
    resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

	has_many :user_events, dependent: :destroy
	has_many :users, through: :user_events

	def save_user_events(params)
	    self.user_events.destroy_all
	    params[:user_id].each do |f|
	      self.user_events.find_or_create_by(user_id: f)
	    end if params[:user_id].present?
	end
end

app/models/user.rb
class User < ApplicationRecord

	has_many :user_events, dependent: :destroy
	has_many :events, through: :user_events
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

  helper_method :current_user

   def current_user
  	 current_user ||= Admin.find_by(id: session[:user_id]) if session[:user_id]
   end

   def require_user
  	 redirect_to login_path unless current_user.present?
   end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user
  before_action :find_event, except: [:index,:new,:create]

  def index
  	if params[:search].present?
      if params[:search][:user_id].present?
  		@user = User.find_by(id: params[:search][:user_id])
  		@events = @user.events.order("event_time asc")
    else
      @events = Event.all.order("event_time asc")
      
    end
  	else
  		@events = Event.all.order("event_time asc")
  	end
  end

  def new
  	@event = Event.new
  end

  def create
		@event = Event.new(event_params)
		if @event.save
			@event.save_user_events(params)
			EventJob.perform_later(params[:user_id],@event)
			flash[:notice] = "You have created an event successfully."
          	redirect_to events_path 
		else
			render 'new'
			flash[:error] = "You are unable create an event.", @event.errors.full_messages
		end
	end

	def edit
	  
	end

	def update
	  if @event.update_attributes(event_params)
	  	@event.save_user_events(params)
	  	redirect_to events_path,:notice => 'Event have updated successfully.'
	  else
	  	redirect_to edit_event_path
	    flash[:alert] = @event.errors.full_messages
	  end
	end
  
  def show
  end

  def destroy
  	@event.destroy
  	redirect_to events_path,:notice => "Event deleted successfully."
  end

  private
  	def find_event
  		@event = Event.find_by(id: params[:id])
  		redirect_to events_path,"Event Not found." unless @event.present?  			
  	end

  	def event_params
	  params.require(:event).permit(:title,:description, :event_time)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	  before_action :require_user

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
    	redirect_to events_path if current_user.present?
    end

  	def create
	    if @user = Admin.find_by(email: params[:session][:email])
	        if @user && @user.valid_password?(params[:session][:password])
	  			session[:user_id] = @user.id
	            flash[:notice] = "You have successfully logged In."
	            redirect_to events_path
	        else
	       		redirect_to login_path
	          flash[:error] = "Invalid Email or Password"
	        end
	    else
	      redirect_to login_path
	      flash[:error] = "Invalid Email, Please try again."
	    end
	end

	def destroy
	    session[:user_id] = nil
	    flash[:success] = "You have successfully logged out."
	    redirect_to login_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

	def options_for_user_select
		User.all.order("name asc").map{|user| [user.name, user.id]}
	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/edit.html.erb
<div class="content-wrapper">
  	<section class="content">
		<div class="container">
			<div class="row">
			    <!-- begin col-6 -->
	    		<div class="col-md-12">		

				<%= form_for @event,url: event_path, method: :patch do |f|%>
					
					<div class="detail-form m-t-40 m-b-40">
						
						<div class="form-group">
							<div class="row">
								<label class="col-sm-4 col-md-3 control-label">Event Name</label>
								<div class="col-sm-8 col-md-7">
								  <%= f.text_field :title, class: "form-control", required: true, placeholder: "Event Name"%>
								</div>
							</div>
						</div>
	
						<div class="form-group">
							<div class="row">
								<label class="col-sm-4 col-md-3 control-label">Event Date & Time</label>
								<div class="col-sm-8 col-md-7" style="position: relative;">
								  <%= f.text_field :event_time, class: "form-control", placeholder: "Select Event Date & Time", required: true, :id=>'datetimepicker1'%>
								</div>
							</div>
						</div>
						
						
						<div class="form-group">
							<div class="row">
								<label class="col-sm-4 col-md-3 control-label">Event Details</label>
								<div class="col-sm-8 col-md-7">
								  <%= f.text_area :description, class: "form-control", required: true, placeholder: "Event Details"%>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="row">
								<label class="col-sm-4 col-md-3 control-label">Event Attaindee</label>
								<div class="col-sm-8 col-md-7">
								   <%= select_tag :user_id, options_for_select(options_for_user_select, @event.user_events.pluck(:user_id)), {multiple: true, class: "form-control", id: "user_selection_ids", required: true}%>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="text-center attendee-cent-s">
								<button class="btn btn-primary m-r-5 m-b-5" type="submit">Submit</button>

							</div>
						</div>
					</div>
				<%end%>
			</div>
		</div>
	</div>
</section>
</div>

<script type="text/javascript">
	$(function () { 
            $('#datetimepicker1').datetimepicker({
            	 format: 'YYYY/MM/DD HH:mm'
            });
        });
</script>

app/views/events/index.html.erb
<script src='http://fullcalendar.io/js/fullcalendar-2.1.1/lib/moment.min.js'></script>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->

   <!-- Main content -->
  <section class="content">

   <div class="box box-info">
 <div class="select-user">
	<%= form_for :search,url: events_path,method: :get do |f|%>
		<%= f.select :user_id,options_for_user_select,value: params[:search], :include_blank => true %>
		<%= f.submit "Search", class: "search-submit"%>
	<%end%>
</div>
<div class="calendar_display">
	<div id="calendar"></div>	
	<div id="events" data-url="<%= @events.to_json %>"> </div>
</div>
<div class="list_display pull-right">
	<%= link_to "Add Event", new_event_path,class: "btn btn-default" %>
	<div class="table-responsive">
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Event Name</th>
				<th>Event Date & Time</th>
				<th>Action</th>											
			</tr>
		</thead>
		
		<% @events.each do |event| %>
			<% unless event.eql?(nil) %>
				<tbody>
					<tr class="even">
						<td><%= event.try(:title) %></td>
						<td><%= event.try(:event_time) %></td>
						<td>
						<a href="/events/<%= event.id%>/edit" class="btn btn-link viewbtn-link m-b-5">Edit</a>
						<a>
						<%= link_to 'Delete'.html_safe, event_path(event.id), method: :delete,:class=>"btn btn-link viewbtn-link m-b-5", data: {confirm: 'Are you sure to delete this event?' }%></a></td> 
					</tr>								
				</tbody>
			<%end%>
		<%end%>
	</table>	
</div>
</div>
</div>
</section>
</div>
<script type="text/javascript">
	$(document).ready(function() {
	    console.log( "ready!" );

	    var event = $('#events').data('url');
  		console.log(event);
  
	  console.log(event.length);
	  var arr = [];
	  for(var i = 0; i < event.length; i++){
		    if(event[i].event_time != null ){
		   h = {};
		   console.log(event[i].event_time);
		   h["date"] = event[i].event_time;
		   h["title"] = event[i].title;
		   h["id"] = event[i].id;
		   arr.push(h);
		 }

		}
       
       $('#calendar').fullCalendar({       
     		events: arr,
     		eventClick: function(calEvent) {
			    document.location.replace(window.location.href + '/' + calEvent.id +'/edit');
			    
			  }
       });
       $("#search_user_id").change(function(){
       	$(".search-submit").click();

       });
	});
</script>

app/views/events/new.html.erb
<div class="content-wrapper">
  	<section class="content">
		<div class="container">
			<div class="row">
			    <!-- begin col-6 -->
	    		<div class="col-md-12">	    	
					<%= form_for @event,url: events_path do |f|%>
						
						<div class="detail-form m-t-40 m-b-40">
							
							<div class="form-group">
								<div class="row">
									<label class="col-sm-4 col-md-3 control-label">Event Name</label>
									<div class="col-sm-8 col-md-7">
									  <%= f.text_field :title, class: "form-control", required: true, placeholder: "Event Name"%>
									</div>
								</div>
							</div>
		
							<div class="form-group">
								<div class="row">
									<label class="col-sm-4 col-md-3 control-label">Event Date & Time</label>
									<div class="col-sm-8 col-md-7" style="position: relative;">
									  <%= f.text_field :event_time, class: "form-control", placeholder: "Select Event Date & Time", required: true, :id=>'datetimepicker1'%>
									</div>
								</div>
							</div>
							
							
							<div class="form-group">
								<div class="row">
									<label class="col-sm-4 col-md-3 control-label">Event Details</label>
									<div class="col-sm-8 col-md-7">
									  <%= f.text_area :description, class: "form-control", required: true, placeholder: "Event Details"%>
									</div>
								</div>
							</div>
							<div class="form-group">
								<div class="row">
									<label class="col-sm-4 col-md-3 control-label">Event Attaindee</label>
									<div class="col-sm-8 col-md-7">
									   <%= select_tag :user_id, options_for_select(options_for_user_select), {multiple: true, class: "form-control", id: "user_selection_ids", required: true}%>
									</div>
								</div>
							</div>
							<div class="form-group">
								<div class="text-center attendee-cent-s">
									<button class="btn btn-primary m-r-5 m-b-5" type="submit">Submit</button>

								</div>
							</div>
						</div>
					<%end%>
				</div>
			</div>
		</div>
	</section>
</div>

<script type="text/javascript">
	$(function () { 
            $('#datetimepicker1').datetimepicker({
            	minDate: 0,
            	 format: 'YYYY/MM/DD HH:mm'
            });

            $('#datetimepicker1').change(function(){
            	alert(this.val());
            });
        });
</script>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/homes/index.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">

  </section>

  <!-- Main content -->
  <section class="content">

   <div class="box box-info">
     <div class="text-right attendee-cent-s form-group">
      <%= link_to "Edit", edit_user_path(id: current_user.id), :class => "btn btn-default btn-green" %>
     </div>
          <!-- /.box-header -->
      <div class="box-body box-profile">
          <div class="profile-box">
          <div class="form-group has-feedback text-center">
            <%#= current_user.image.present? ? image_tag(current_user.image.url,:width => 100, :height => 100, :class => 'profile-ab') : image_tag("/1.png",:width => 100, :height => 100, :class => 'profile-ab') %>
          </div>
          <h3 class="profilecurrent_username text-center"><%= current_user.email%></h3>
          <p class="text-muted text-center"><%#= current_user.address%></p>

        <div class="profile-inner">
        	<div class="p-blocks">
              <label class="view-a left-a">Account Number</label>
              <span class="view-a right-a"><%#= current_user.bank_account.try(:account_no) %></span>
          </div>
          <div class="p-blocks">
              <label class="view-a left-a">Available Balance</label>
              <span class="view-a right-a"><%#= current_user.bank_account.try(:account_balance) %></span>
          </div>
         
          <div class="p-blocks">
              <label class="view-a left-a">Name</label>
              <span class="view-a right-a"><%#= current_user.name%></span>
          </div>
          <!-- <div class="p-blocks">
              <label class="view-a left-a">Gender</label>
              <span class="view-a right-a"><%#= current_user.email%></span>
          </div> -->
          <div class="p-blocks">
              <label class="view-a left-a">Date of birth</label>
              <span class="view-a right-a"><%#= current_user.dob%></span>
          </div>
          <div class="p-blocks">
              <label class="view-a left-a">Email</label>
              <span class="view-a right-a"><%#= current_user.email%></span>
          </div>
          <div class="p-blocks">
              <label class="view-a left-a">Mobile</label>
              <span class="view-a right-a"><%#= current_user.mobile%></span>
          </div>
          <div class="p-blocks">
              <label class="view-a left-a">Address</label>
              <span class="view-a right-a"><%#= current_user.address%></span>
          </div>
      </div>

          </div>
      </div>
    </div>

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <div class="row flash-alerts">
    <div class = 'alert alert-dismissable alert-info'>
      <button type="button" class="close" data-dismiss="alert">×</button>
      <% flash.each do |name, msg| %>
        <%= content_tag :h5, msg %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%#= javascript_include_tag :defaults, "nested_form" %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css">
  <%#= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%#= favicon_link_tag '/favicon.png', :rel => 'shortcut icon' %>

  <!-- <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"> -->

</head>
<%if current_user %>
<body class="hold-transition skin-red sidebar-mini fixed">
<div class="wrapper">

  <header class="main-header">
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">

    <a class="sidebar-toggle menu-txt" id="id-sidebar-toggle" role="button" data-toggle="offcanvas" href="#">
    <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
     <ul class="nav navbar-nav">
    <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle menu-txt" data-toggle="dropdown">
            <span class="hidden-xs"><%= current_user.email.present? ? current_user.email : "Admin" %></span>
          </a>
          <ul class="dropdown-menu">
         
            <!-- Menu Footer-->
            <li class="user-footer">
              
              <div class="pull-right">
                <%= link_to "Sign out", logout_path,:class=>"btn btn-default btn-flat", method: :delete %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>


  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can bMerchandisee found in sidebar.less -->
    <section class="sidebar">
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        
           
          <li class="treeview">
            <a class="menu-txt" href="/events">
              <i class="fa fa-calendar"></i> <span>Events</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-right pull-right"></i>
              </span>
            </a>
          </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
  </div>

<%end%>
            <%= render :partial => "layouts/flash" %>

            <%= yield %>

<%if current_user%>
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; <%= Time.current.strftime("%Y")%> <a href="https://www.google.com/" class="fans-link">DemoTest</a>.</strong> All rights
    reserved.
  </footer>
<%end%>

</body>
</html>